apiVersion: apps/v1
kind: Deployment
metadata:
  name: roseaw-cyberrange-deployment
spec:
  replicas: 2  # Number of NGINX pods to run
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: cithit/roseaw-cyberrange:latest
        ports:
        - containerPort: 5000  # Expose NGINX on port 5000      
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-app
spec:
  rules: 
  - host: 
    http:
      paths:
      - path: 
        pathType: ImplementationSpecific
        backend: 
          service:
            name: flask-app-internal-service
            port:
              number: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-internal-service
spec:
  type: LoadBalancer 
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  selector:
    app: flask-app 
