apiVersion: apps/v1
kind: Deployment
metadata:
  name: roseaw-cyberrange-deployment
spec:
  replicas: 2  # Number of NGINX pods to run
  selector:
    matchLabels:
      app: app-py
  template:
    metadata:
      labels:
        app: app-py
    spec:
      containers:
      - name: app-py
        image: cithit/roseaw-cyberrange:latest
        ports:
        - containerPort: 5000  # Expose NGINX on port 80      
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-py
spec:
  rules: 
  - host: 
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend: 
          service:
            name: app-py-internal-service
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-py-internal-service
spec:
  type: LoadBalancer 
  loadBalancerIP: 10.48.10.112
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: app=py 
